sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - 'nvm install 6.9.1 && npm i -g grunt' # Install NodeJS deps
  - 'sudo n lts' # Bump NPM to LTS version
install:
  - 'cd app && npm i'
  - 'cd ..'
script:
  - 'cd spigot && mvn test'
  - 'cd ../app && npm test'
  - 'cd ..'
