sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - 'npm i -g n grunt' # Install NodeJS deps
  - 'sudo n lts' # Bump NPM to LTS version
install:
#  - 'npm i'
script:
  - 'mvn test'
#  - 'grunt test'
